# This list contains domains that use default rules.
# Custom domains from 'lib/domains' included automatically.

-
  id: vimeo.com
  config:
    autoplay: autoplay=1
-
  id: rutube.ru
  config:
    autoplay: autoStart=true
